# Generated by Django 3.1.3 on 2020-11-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Physical_Training_Leader',
            new_name='PhysicalTrainingLeader',
        ),
        migrations.RenameModel(
            old_name='Unit_Fitness_Program_Manager',
            new_name='UnitFitnessProgramManager',
        ),
    ]
