# Generated by Django 3.1.3 on 2020-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_auto_20201128_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airman',
            options={'ordering': ('last_name',), 'verbose_name': 'Airman', 'verbose_name_plural': 'Airmen'},
        ),
        migrations.AlterModelOptions(
            name='naughty',
            options={'ordering': ('-failure_date',), 'verbose_name': 'Failure, Unsatisfactory, & Non-Current', 'verbose_name_plural': 'Failures, Unsatisfactory, & Non-Currents'},
        ),
        migrations.AlterModelOptions(
            name='physicaltrainingleader',
            options={'ordering': ('ptl_expiration_date',), 'verbose_name': 'PTL', 'verbose_name_plural': 'PTLs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('profile_expiration_date',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='unitfitnessprogrammanager',
            options={'ordering': ('ufpm_expiration_date',), 'verbose_name': 'UFPM', 'verbose_name_plural': 'UFPMs'},
        ),
        migrations.AlterField(
            model_name='airman',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='airman',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airman',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
