# Generated by Django 3.1.3 on 2020-11-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_auto_20201128_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airman',
            options={'ordering': ('last_name',), 'verbose_name': 'Airman', 'verbose_name_plural': 'AIRMEN'},
        ),
        migrations.AlterModelOptions(
            name='naughty',
            options={'ordering': ('-failure_date',), 'verbose_name': 'Failure, Unsatisfactory, & Non-Current', 'verbose_name_plural': 'FAILURE, UNSATISFACTORY, & NON-CURRENTS'},
        ),
        migrations.AlterModelOptions(
            name='physicaltrainingleader',
            options={'ordering': ('ptl_expiration_date',), 'verbose_name': 'Physical Training Leader', 'verbose_name_plural': 'PHYSICAL TRAINING LEADERS'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('profile_expiration_date',), 'verbose_name': 'Profile', 'verbose_name_plural': 'PROFILES'},
        ),
        migrations.AlterModelOptions(
            name='unitfitnessprogrammanager',
            options={'ordering': ('ufpm_expiration_date',), 'verbose_name': 'Unit Fitness Program Manager', 'verbose_name_plural': 'UNIT FITNESS PROGRAM MANAGERS'},
        ),
    ]
