# Generated by Django 3.1.1 on 2020-12-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_auto_20201201_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='rank',
            field=models.CharField(choices=[('E-1/AB', 'E-1/AB'), ('E-2/Amn', 'E-2/Amn'), ('E-3/A1C', 'E-3/A1C'), ('E-4/SrA', 'E-4/SrA'), ('E-5/SSgt', 'E-5/SSgt'), ('E-6/TSgt', 'E-6/TSgt'), ('E-7/MSgt', 'E-7/MSgt'), ('E-8/SMSgt', 'E-8/SMSgt'), ('E-9/CMSgt', 'E-9/CMSgt'), ('O-1/2nd Lt', 'O-1/2nd Lt'), ('O-2/1st Lt', 'O-2/1st Lt'), ('O-3/Capt', 'O-3/Capt'), ('O-4/Maj', 'O-4/Maj'), ('O-5/Lt Col', 'O-5/Lt Col'), ('O-6/Col', 'O-6/Col'), ('O-7/Brig Gen', 'O-7/Brig Gen'), ('O-8/Maj Gen', 'O-8/Maj Gen'), ('O-9/Lt Gen', 'O-9/Lt Gen'), ('O-10/Gen', 'O-10/General')], default='E-1/AB', max_length=15),
        ),
    ]
