# Generated by Django 3.1.3 on 2021-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0006_auto_20201201_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='airman',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
