# Generated by Django 3.1.3 on 2021-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0007_airman_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15),
        ),
    ]
