# Generated by Django 3.1.3 on 2021-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_auto_20210216_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='airman',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
